### PR TITLE
Tiny bit of efficiency gains

### PR DESCRIPTION
**Pull request by something23-0001**
Re-factor some code for efficiency purposes, rather than having to define everything in 2-3 lines

Do appreciate your work!

### CODE REVIEW

**Comment by beingisdead** [comment]
I appreciate what you've done but I will not accept pull requests until the new version of SKeRM is released (hopefully in a few days). This version is unorganized, messy and inefficient.

**Comment by something-0001** [comment]
Perhaps push this? I've seen no update and I'm just looking through old PR's lol

**Comment by beingisdead** [comment]
This project is dead and will not be continued due to updates made to the GitHub API.

**Comment by something-0001** [comment]
Fair enough!

**Pull request closed without merging**
